/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 06-May.-2019 23:58:53 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Create Tables */

use Proyecto_DIARS_ISIS

Create TABLE [Comprobantepagoreserva]
(
	[Fechadeemision] date NULL,
	[Ruc] char(11) NULL,
	[ComprobantepagoreservaID] int PRIMARY KEY NOT NULL,
	[ReservaID] int IDENTITY(1,1) NOT NULL,
	[Monto] decimal(18,0) NULL
)
GO

CREATE TABLE [Comprobantepagoalquiler]
(
	[Fechadeemision] date NULL,
	[Ruc] char(11) NULL,
	[ComprobantepagoalquilerID] int PRIMARY KEY NOT NULL,
	[AlquilerID] int IDENTITY(1,1) NOT NULL,
	[Monto] decimal(18,0) NULL
)
GO

CREATE TABLE [ServAdicionalTipoH]
(
	[TipodehabitacionID] int NULL,
	[ServAdicTipoH] int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[ServicioadicionalID] int NOT NULL
)
GO

CREATE TABLE [Servicioadicional]
(
	[NombreServicionvarchar(50) NULL,
	[ServicioadicionalID] int IDENTITY(1,1) PRIMARY KEY NOT NULL
)
GO

CREATE TABLE [dbo].[Alquiler]
(
	[CantidadAdultos] [int] NOT NULL,
	[CantidadKids] [int] NOT NULL,
	[Fechadeingreso] [date] NOT NULL,
	[Fechadesalida] [date] NOT NULL,
	[AlquilerID] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Dni] [char](8) NOT NULL,
	[NumeroHabitacion] nvarchar(4) NOT NULL,
)
GO

CREATE TABLE [AlquilerControl]
(
	[AlquilerControlID] int identity(1,1) Primary Key Not Null,
	[Entrada] datetime Not Null,
	[Salida] datetime Null,
	[AlquilerID] int Not Null
)	
GO

CREATE TABLE [dbo].[Reserva]
(
	[CantidadAdultos] [int] NOT NULL,
	[CantidadKids] [int] NOT NULL,
	[FechadeIngreso] [date] NOT NULL,
	[FechadeSalida] [date] NOT NULL,
	[Fechadereserva] [date] NULL,
	[ReservaID] [int] IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[Dni] [char](8) NOT NULL,
	[NumeroHabitacion] nvarchar(4) NOT NULL,
)
GO

CREATE TABLE [dbo].[Habitacion]
(
	[NumeroHabitacion] nvarchar(4) PRIMARY KEY NOT NULL,
	[TipodehabitacionID] [int] NOT NULL,
)
GO

CREATE TABLE [dbo].[Tipodehabitacion](
	[Capacidad] [int] NULL,
	[Costoadicional] [decimal](6, 2) NULL,
	[Nombretipodehabitacion]nvarchar](50) NULL,
	[Numerodecamas] [int] NULL,
	[Precio] [decimal](6, 2) NULL,
	[TipodehabitacionID] [int] PRIMARY KEY NOT NULL,
)
GO

/*NEW*/

Create TABLE [Huesped]
(
	[Dni] [char](8) PRIMARY KEY NOT NULL,
	[NombreUsuario] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [Recepcionista]
(
	[RecepcionistaID] int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[NombreUsuario] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [UserAccount]
(
	[UserName] nvarchar(50) PRIMARY KEY NOT NULL,
	FechaNacimiento datetime,
	Nombre nvarchar(50),
	Apellidos nvarchar(50)
)
GO

Create TABLE [Cuenta]
(
	[Email] nvarchar(50) PRIMARY KEY NOT NULL,
	[FechaCreacion] datetime NOT NULL,
	[UserName] nvarchar(50) NOT NULL
)
GO

CREATE TABLE [Passwordaccount]
(
	[Passwordstring] nvarchar(350) NULL,
	[HashCode] nvarchar(50) NULL,
	[PasswordaccountID] int IDENTITY(1,1) NOT NULL
)
GO

CREATE TABLE HashTable
(
	[HashCode] nvarchar(50) PRIMARY KEY NOT NULL,
)
GO

CREATE TABLE [AccountHashTable]
(
	[HashCode] nvarchar (50),
	[Email] nvarchar(50),
	[Activa] bit,
	[AccountHashTableID] int IDENTITY(1,1) PRIMARY KEY NOT NULL
)
go


ALTER TABLE [Huesped] ADD CONSTRAINT [FK_User_Huesped]
	FOREIGN KEY ([UserName]) REFERENCES [UserAccount] ([UserName]) ON DELETE Cascade ON UPDATE No Action
GO

ALTER TABLE [Recepcionista] ADD CONSTRAINT [FK_User_Recep]
	FOREIGN KEY ([UserName]) REFERENCES [UserAccount] ([UserName]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Cuenta] ADD CONSTRAINT [FK_Account_User]
	FOREIGN KEY ([UserName]) REFERENCES [UserAccount] ([UserName]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Passwordaccount] ADD CONSTRAINT [FK_Password_Hash]
	FOREIGN KEY ([HashCode]) REFERENCES [HashTable] ([HashCode]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [AccountHashTable] ADD CONSTRAINT [FK_Account_Hash]
	FOREIGN KEY ([HashCode]) REFERENCES [HashTable] ([HashCode]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [AccountHashTable] ADD CONSTRAINT [FK_Account_Cuenta]
	FOREIGN KEY ([Email]) REFERENCES [Cuenta] ([Email]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Alquiler] ADD CONSTRAINT [FK_Alquiler_Huesped]
	FOREIGN KEY ([Dni]) REFERENCES [Huesped] ([Dni]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Alquiler] ADD CONSTRAINT [FK_Alquiler_Habitacion]
	FOREIGN KEY ([NumeroHabitacion]) REFERENCES [Habitacion] ([NumeroHabitacion]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Reserva] ADD CONSTRAINT [FK_Reserva_Huesped]
	FOREIGN KEY ([Dni]) REFERENCES [Huesped] ([Dni]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Reserva] ADD CONSTRAINT [FK_Reserva_Habitacion]
	FOREIGN KEY ([NumeroHabitacion]) REFERENCES [Habitacion] ([NumeroHabitacion]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Habitacion] ADD CONSTRAINT [FK_Habitacion_Tipodehabitacion]
	FOREIGN KEY ([TipodehabitacionID]) REFERENCES [Tipodehabitacion] ([TipodehabitacionID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [AlquilerControl] ADD CONSTRAINT [FK_AlquilerControl_Alquiler]
	FOREIGN KEY ([AlquilerID]) REFERENCES [Alquiler] ([AlquilerID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Comprobantepagoalquiler] ADD CONSTRAINT [FK_Comprobantepagoalquiler_Alquiler]
	FOREIGN KEY ([AlquilerID]) REFERENCES [Alquiler] ([AlquilerID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Comprobantepagoreserva] ADD CONSTRAINT [FK_ReservaID]
	FOREIGN KEY ([ReservaID]) REFERENCES  [Reserva] ([ReservaID]) ON DELETE No Action ON UPDATE No Action
GO


ALTER TABLE [ServAdicionalTipoH] ADD CONSTRAINT [FK_ServicioAdicionalTipoDeHabitacion_TipoDeHabitacion]
	FOREIGN KEY ([TipodehabitacionID]) REFERENCES [Tipodehabitacion] ([TipodehabitacionID]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ServAdicionalTipoH] ADD CONSTRAINT [FK_ServicioAdicionalTipoDeHabitacion_ServicioAdicional]
	FOREIGN KEY ([ServicioadicionalID]) REFERENCES [Servicioadicional] ([ServicioadicionalID]) ON DELETE No Action ON UPDATE No Action
GO